name: Cpp porject with gtest

on: [push]

jobs:
  build:
    runs-on: self-hosted

    env:
      CC:  gcc
      CXX: g++

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check for bad words
      run: "! grep -R -n -w -f .bad_words src include"
    
    - name: Run clang format
      run: find . -iname "*.h" -o -iname "*.hpp" -o -iname "*.cpp" -exec clang-format --dry-run --Werror -style=file {} +

    - name: Build default
      run: mkdir build && cmake -S. -Bbuild -DUSE_CLANG_TIDY=TRUE -DTESTS_BUILD_TYPE=NONE -DCMAKE_BUILD_TYPE=Release && cmake --build build
    - name: Run default tests
      timeout-minutes: 3
      working-directory: ./tests
      run: ./Run-tests
