name: C++ Project with Catch2 Testing

on: [push]

jobs:
  build:
    runs-on: self-hosted
    env:
      CC: gcc
      CXX: g++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check for bad words
      run: "! grep -R -n -w -f .bad_words src include"
    
    - name: Run clang-format
      run: find . -iname "*.h" -o -iname "*.hpp" -o -iname "*.cpp" -exec clang-format --dry-run --Werror -style=file {} +

    # Regular tests build
    - name: Build default
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel
      
    - name: Run default tests
      timeout-minutes: 3
      working-directory: ./build/tests
      run: ./Run-tests

    # ASAN build
    - name: Build ASAN
      run: |
        mkdir -p build_asan && cd build_asan
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=address
        cmake --build . --parallel
      
    - name: Run ASAN tests
      timeout-minutes: 5
      working-directory: ./build_asan/tests
      run: ./Run-tests

    # UBSAN build
    - name: Build USAN
      run: |
        mkdir -p build_ubsan && cd build_ubsan
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=undefined
        cmake --build . --parallel
      
    - name: Run USAN tests
      timeout-minutes: 5
      working-directory: ./build_ubsan/tests
      run: ./Run-tests
