name: C++ Project with Catch2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Changed from self-hosted to GitHub-hosted runner

    env:
      CC: gcc
      CXX: g++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Check for bad words
      run: "! grep -R -n -w -f .bad_words src include tests"  # Added tests directory

    - name: Run clang format
      run: find . -iname "*.h" -o -iname "*.hpp" -o -iname "*.cpp" -exec clang-format --dry-run --Werror -style=file {} +

    - name: Build default
      run: |
        mkdir build && 
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && 
        cmake --build build

    - name: Run default tests
      timeout-minutes: 3
      working-directory: ./build/tests
      run: ./Run-tests

    - name: Build ASAN
      run: |
        mkdir build_ASAN && 
        cmake -S. -Bbuild_ASAN -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fsanitize=address" && 
        cmake --build build_ASAN

    - name: Run ASAN tests
      timeout-minutes: 5
      working-directory: ./build_ASAN/tests
      run: ./Run-tests

    - name: Build USAN
      run: |
        mkdir build_USAN && 
        cmake -S. -Bbuild_USAN -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fsanitize=undefined" && 
        cmake --build build_USAN

    - name: Run USAN tests
      timeout-minutes: 5
      working-directory: ./build_USAN/tests
      run: ./Run-tests
